$(document).ready(function(){
    //var secrets = [];
    //var readout = function(text){
            //var msg = new SpeechSynthesisUtterance(text);
            //window.speechSynthesis.speak(msg);
    //}
    $("input").autocomplete({
        source: src,              // can be a f(request, response)
                                    // OR a "http://example.com", which will be queried with the user-inputed string"
        autoFocus: true,          // def: false
        classes: {},
        delay: 500,               // def: 300
        disabled: false,
        minLength: 3,             // def: 1
        position: { my: "left top", at: "left bottom", collision: "none"},

        
    });


});

var src = [
"What is the step by step guide to invest in share market in india?",
"What is the story of Kohinoor (Koh-i-Noor) Diamond?",
"How can I increase the speed of my internet connection while using a VPN?",
"Why am I mentally very lonely? How can I solve it?",
"Which one dissolve in water quikly sugar, salt, methane and carbon di oxide?",
"Astrology: I am a Capricorn Sun Cap moon and cap rising...what does that say about me?",
"Should I buy tiago?",
"How can I be a good geologist?",
"When do you use シ instead of し?",
"Motorola (company): Can I hack my Charter Motorolla DCX3400?",
"Method to find separation of slits using fresnel biprism?",
"How do I read and find my YouTube comments?",
"What can make Physics easy to learn?",
"What was your first sexual experience like?",
"What are the laws to change your status from a student visa to a green card in the US, how do they compare to the immigration laws in Canada?",
"What would a Trump presidency mean for current international master’s students on an F1 visa?",
"What does manipulation mean?",
"Why do girls want to be friends with the guy they reject?",
"Why are so many Quora users posting questions that are readily answered on Google?",
"Which is the best digital marketing institution in banglore?",
"Why do rockets look white?",
"What's causing someone to be jealous?",
"What are the questions should not ask on Quora?",
"How much is 30 kV in HP?",
"What does it mean that every time I look at the clock the numbers are the same?",
"What are some tips on making it through the job interview process at Medicines?",
"What is web application?",
"Does society place too much importance on sports?",
"What is best way to make money online?",
"How should I prepare for CA final law?",
"What's one thing you would like to do better?",
"What are some special cares for someone with a nose that gets stuffy during the night?",
"What Game of Thrones villain would be the most likely to give you mercy?",
"Does the United States government still blacklist (employment, etc.) some United States citizens because their political views?",
"What is the best travel website in spain?",
"Why do some people think Obama will try to take their guns away?",
"I'm a 19-year-old. How can I improve my skills or what should I do to become an entrepreneur in the next few years?",
"How do we prepare for UPSC?",
"What is the stall speed and AOA of an f-14 with wings fully swept back?",
"Why do Slavs squat?",
"When can I expect my Cognizant confirmation mail?",
"Can I make 50,000 a month by day trading?",
"Is being a good kid and not being a rebel worth it in the long run?",
"What universities does Rexnord recruit new grads from? What majors are they looking for?",
"What is the quickest way to increase Instagram followers?",
"How did Darth Vader fought Darth Maul in Star Wars Legends?",
"What are the stages of breaking up between couple? I mean, what happens after the breaking up emotionally whether its a male or female?",
"What are some examples of products that can be make from crude oil?",
"How do I make friends.",
"Is Career Launcher good for RBI Grade B preparation?",
"Will a Blu Ray play on a regular DVD player? If so, how?",
"Nd she is always sad?",
"What is the best/most memorable thing you've ever eaten and why?",
"How GST affects the CAs and tax officers?",
"How difficult is it get into RSI?",
"Who is israil friend?",
"What are some good rap songs to dance to?",
"I was suddenly logged off Gmail. I can't remember my Gmail password and just realized the recovery email is no longer alive. What can I do?",
"What are the best ways to learn French?",
"How do I download content from a kickass torrent without registration?",
"Is it normal to have a dark ring around the iris of my eye?",
"How is the new Harry Potter book 'Harry Potter and the Cursed Child'?",
"Why do I always get depressed?",
"Where can I find a European family office database?",
"What is Java programming? How To Learn Java Programming Language ?",
"What is the best book ever made?",
"Can we ever store energy produced in lightning?",
"What is your review of Performance Testing?",
"At what cost does so much privacy as in Germany come? What else is lost to gain so much privacy?",
"What are the types of immunity?",
"What is a narcissistic personality disorder?",
"How I can speak English fluently?",
"How helpful is QuickBooks' auto data recovery support phone number to recover your corrupted data files?",
"Who is the richest gambler of all time and how can I reach his level?",
"If I fire a bullet backward from an aircraft going faster than the bullet; will the bullet be going backwards?",
"How do I prevent breast cancer?",
"How do I log out of my Gmail account on my friend's phone?",
"How can I make money through the Internet?",
"What is purpose of life?",
"When will the BJP government strip all the Muslims and the Christians of the Indian citizenship and put them on boats like the Rohingya's of Burma?",
"What is the right etiquette for wishing a Jehovah Witness happy birthday?",
"If someone wants to open a commercial FM radio station in any city of India, how much does it cost and what is the procedure?",
"Why do Swiss despise Asians?",
"What are some of the high salary income jobs in the field of biotechnology?",
"How can I increase my height after 21 also?",
"What were the major effects of the cambodia earthquake, and how do these effects compare to the Kamchatca earthquakes in 1952?",
"What is the difference between sincerity and fairness?",
"Which is the best gaming laptop under 60k INR?",
"What is your review of The Next Warrior: Proving Grounds - Part 9?",
"What is the best reference book for physics class 11th?",
"National Institute of Technology, Kurukshetra: How is the social life at NITK, Surathkal?",
"What are some of the best romantic movies in English?",
"What causes a nightmare?",
"What is abstract expressionism in painting?",
"How does 3D printing work?",
"What was it like to attend Caltech with Jeremy Ehrhardt?",
"Why did harry become a horcrux?",
"What are the best associate product manager (APM) programs that someone in their early 20s can join to learn product management and have a rewarding career in the company?",
"Why is the number for Skype at 1-855-425-3768 always busy?",
"Will there really be any war between India and Pakistan over the Uri attack? What will be its effects?",
"Did Ronald Reagan have a mannerism in his speech?",
"What were the war strategies of the Union and the Confederates during the Civil War?",
"Which is the best fiction novel of 2016?",
"Can I recover my email if I forgot the password?",
"Will the recent demonetisation results in higher GDP? If so how much?",
"Have you ever heard of travel hacking?",
"What's the difference between love and pity?",
"How competitive is the hiring process at Republic Bank?",
"How Google helps in spam ranking adjustment of the search results?",
"Where can I watch gonulcelen with english subtitles?",
"Is USA the most powerful country of the world?",
"How do you obtain an instant ulcer pain relief?",
"What do you think China food?",
"What does taking advantage of someone mean?",
"Why do we cry when we are happy and when we are sad?",
"Why do some girls like to stick their their tongues out when taking pictures?",
"What are some mind-blowing computer tools that exist that most people don't know about?",
"Should the toothbrush be wet or dry before applying the toothpaste?",
"Why my question was marked as needing imrovement?",
"What is the difference between a neutral state and a buffer state?",
"What mineral holds the highest electrical charge?",
"What is the greatest mystery in the universe?",
"What is the alternative to machine learning?",
"Why does China block sanctions at the UN against the Jaish-e-Mohammad (JeM) chief, Masood Azhar?",
"What is the mean of future budget?",
"Can excessive amounts of Vitamin C cause me to have a miscarriage?",
"What is it like to work in Asahi India Glass? What will be the pay scale after one or two years?",
"How do I access Torbox in India?",
"What are some yakshini mantras?",
"Was six party talks successful?",
"How do I register my domain site email?",
"Is it normal for older men to be attracted to young women?",
"What is the strongest structure or strongest shape under compression?",
"Who are the Rohingya Muslims?",
"Does it matter whether humans are selfish or evil?",
"Are exocytosis and endocytosis examples of active or passive transport?",
"How i get hair on bald head?",
"What is the ideal life after retirement?",
"What is our stance against Pakistan?",
"What are good websites for escorts?",
"Which one is better polo diesel or grand i10 petrol?",
"Does a black hole have mass?",
"Is Morgan Freeman correct when he says the only way to stop racism, is to stop talking about it?",
"Does Fab currently offer new employees stock options or RSUs?",
"How would you review the site Waveclues?",
"In how many ways can we distribute 10 identical looking pencils to 4 students so that each student gets at least one pencil?",
"How much would it cost to hire Jerry Seinfeld for 1-2 hours?",
"Is 7 days too late for rabies vaccine after a possible non-bite exposure?",
"How many years Britain ruled India?",
"How can I stop being afraid of working?",
"Why does Red keep the keys in OITNB?",
"At what age should someone lose their virginity?",
"How forgetful are you?",
"Could Snoke secretly be Darth Maul?",
"If I do not monetize YouTube videos & upload copyright content, then are there chances that Google may block my account?",
"Would you switch from Canon 6D to Leica D-LUX 109?",
"What does the Quora website look like to members of Quora moderation?",
"Why nobody answer my questions in Quora?",
"What is the funniest joke you know?",
"I got job offer @ Chelmsford-Essex, London with £3764 PM pay-after tax deduction. Pls advice tentative monthly expenses for couple? & saving possible?",
"What are stereotypes about the United Kingdom?",
"How do I use Twitter as a business source?",
"How can I transfer money from Skrill to a PayPal account?",
"Which is the best earphone with deep bass under 1000?",
"Are government employees eligible to Sukanya Samrudi Yojana?",
"Which is correct - 'Looking forward to speak with you' or 'Look forward to speak with you'?",
"Which are the best engineering fields?",
"How do you make life suit you and stop life from abusing you mentally and emotionally?",
"What is the difference between gross salary and CTC?",
"Which are the prospering towns in Kerala?",
"What is the best way to gain confidence?",
"Does anyone see the relation between Greek gods and Hindu gods?",
"How do I switch from Apple Music to Spotify?",
"Which is the best fixed income fund?",
"What is it like to live in Cologne?",
"Between Robert De Niro and Al Pacino, who is more successful?",
"Why does some people prefer small families.?",
"Do animals kiss?",
"How do you get deleted Instagram chats?",
"How can I stop being addicted to love?",
"What if I hired two private eyes and ordered them to follow each other?",
"How do I find a startup accelerator?",
"How can I check wifi history and access it through android phones?",
"What was the significance of the battle of Somme, and how did this battle compare and contrast to the Battle of Rostov?",
"What is the most creative college admissions essay you've read?",
"What would happen if you cover one of your eyes with an eye patch for one year, then take the patch off?",
"Is it possible to pursue many different things in life?",
"Did Ben Affleck shine more than Christian Bale as Batman?",
"Which business is good start up in Hyderabad?",
"How can I stop being so possessive?",
"Who was the wife of Lord Krishna?",
"What is the best combination of courses I can take up along with CA to enhance my career?",
"How do you take a screenshot on a Mac laptop?",
"What is the work of an executive recruiter like?",
"Which psychological need does 'collecting' fulfill?",
"What are some must watch TV shows before you die?",
"How can I become more fluent in Chinese?",
"What are the effects of demonitization of 500 and 1000 rupees notes on real estate sector?",
"What is the easiest way to become a billionaire($)?",
"Are there People who are willing to give free lectures or conduct free workshop in India colleges?",
"What's the best way to start learning robotics?",
"Why do people hate Hillary Clinton?",
"Why are women who are on their periods are regarded as 'unclean' such that they are prevented in taking an actived part in rituals (Hinduism)?",
"If atheism is the lack of belief in gods, what is the term for the belief that there is no god?",
"What is it like to be Jack Dorsey?",
"What are the best quotes/lessons of the Assassin's Creed series?",
"Do inkjet printers use color ink when printing black and white documents? If so, why?",
"Why is creativity important?",
"If Hillary Clinton could not continue her Presidential campaign how would the Democratic Party choose a new candidate?",
"How headphones work as an Antenna to play FM radio channels on Mobile phones? Why mobile companies doesn't install the same inbuilt Antenna on phones to be able to play FM without the headphones?",
"What are the best career growth technologies for automation engineers apart from automation tools?",
"What are the disadvantages of listing a company in NSE?",
"How many derivatives of an object's position with respect to time have to be continuous?",
"Is the neutron star made up of?",
"I got a 3.8 GPA. Is it enough to get into top universities like Harvard?",
"What is a profitable way to trade binary options?",
"How do I utilize free time to avoid depression?",
"How can I learn computer security?",
"How do I earn from Quora?",
"What is my puk code?",
"How can I find job in Japan?",
"Will there be another billion dollar lottery Jackpot?",
"How scary is it to drive on the road to Hana given all of the turns?",
"How do I create a new shell in a new terminal using C programming (Linux terminal)?",
"Does cognition affect perception?",
"How TQWL is different from CKWL (Tatkal waiting list)?",
"How can we make the world a better place to live in for the future generations?",
"How many Champions are there in League of Legends?",
"Is drinking 4 liters of water each day unhealthy?",
"Where does the water from the Great Lakes come from, and how does these lakes wildlife compare to Lake Prespa?",
"Do porn stars watch porn?",
"Trump supporters, how do you feel about the way he's walking back his promises?",
"Why are we worried about others' opinions?",
"How do you potty train a 4 months Pitbull?",
"If I jump rope for five minutes, how many calories will I use?",
"Which online test series is best for GATE 2017 in CS stream?",
"What is the best material for understanding algorithmic analysis by a newbie?",
"What is the temperament of a Bullmastiff/Husky mix?",
"There are 8 balls. 7 of them weigh the same. 1 of them has a different weight, (you don't know if it's heavier or lighter). How do you find the odd ball with 2 weighs?",
"What are the signs of an ultra smart person playing dumb?",
"If dark energy is created with expansion can infinite of it be created?",
"How do you get a book published?",
"Who is disrupting Bloomberg?",
"Why can flash run so fast?",
"What is the best way to invest $500 legally so that I can get tangible profits over a relatively short period of time, say 6 months?",
"How will the implementation of GST bill impact the lives of common people?",
"How can you recover your Gmail password?",
"How accurately can a mental illness can be diagnosed?",
"Is knee pain in a 20 year old girl normal?",
"What are the qualities of a good leader?",
"What is the difference between bay, gulf and straits?",
"Will Modi win in 2019?",
"How can I open DMart store in India? Is there any franchise for that?",
"What are the best YouTube channels to learn medicine?",
"Did Swami Vivekananda ever eat non-veg or egg during his journey around the world?",
"What will happen if I cancel TQWL tickets before the charting is done?",
"How do I choose a journal to publish my paper?",
"What are your New Year's resolutions for 2017?",
"What do you do if you had a bad dream?",
"Why do Slavs squat?",
"How many marks should I score for AIIMS rank 151?",
"In an operating room, when two surgeons of equal experience disagree on a surgical procedure, how is the tie broken?",
"How many months does it take to gain knowledge in developing Android apps from scratch?",
"How do I love my body as a guy?",
"What are the rights of a prisoner?",
"How can I get free gems in Clash of Clans?",
"Why aren't there more apps like Word Lens?",
"My ex-girlfriend is suffering from malaria. I have a deep urge of visiting her but I have my placements on. I have no idea how to be with her. What should I do?",
"What is the best way to get traffic on your website?",
"How do you feel when someone upvotes your answer on Quora?",
"What are some of the best films and TV shows that feature strong female protagonists?",
"How far would you go for love? Should I wait for the one I love ir move on?",
"How do most people die?",
"Why are most clothes made of polyester now instead of cotton?",
"What is in bone marrow?",
"Were there any slave with the name Reddice?",
"How long does it take for a dead body to float to the surface after drowning ?",
"How do I get over a friend with whom I haven't talked in 3 years but still miss him?",
"When travelling to a new region is it better to immerse yourself in 1–2 cities or to see as many cities as you can cram in?",
"How can I make money online with free of cost?",
"Where can I buy best quality customized cupcakes in Gold Coast?",
"How successful was odd even plan?",
"If there will be a war between India and Pakistan who will win?",
"How do you deal with a fear of dying?",
"What would be the estimated cost of repairing the cracked screen of iphone 6?",
"What are the most interesting products and innovations that McDonald's is coming out with in 2016?",
"Is there an end to the universe, and if not, is the universe infinite?",
"What is CPAGrip.com?",
"How much funds should I raise?",
"What Anna Hazare think about PM Modi?",
"What will be the effect of banning 500 and 1000 notes on stock markets in India?",
"How does concentric contractions differ from eccentric contractions?",
"Why did the puppet they used for Yoda in Episode I suck so bad?",
"On what online platforms can I post ads for beer money opportunity?",
"What the meaning of this all life?",
"How should I start small business effectively?",
"How can we acquire a positive morality?",
"Do you need friends?",
"Do I exist?",
"Which are the best Hollywood thriller movies?",
"Should I repeat 2nd year in college, or find a new college? It's a 5 year course.",
"How is petrol or diesel pumped up in a filling station using a motor without igniting any fire?",
"What job possibilities exist for a Bachelors in Homeland Security?",
"Which are the best books to understand calculus?",
"Why and how did you break up with her/him?",
"Can I use Jio SIM in iPhone 5s?",
"What are some unwritten rules in USA?",
"What is the best answer to what you did in two years gap in a job interview?",
"What are the best songs for low voices?",
"Can anyone predict my birth chart?",
"When was the birth of the trigonometric functions?",
"What do countries do to prevent war?",
"How can I become a billionaire?",
"Why should I learn web design?",
"What's the best on-line calender/scheduling/booking system? Something that allows me to show my availability & customers can 'request' to meet me. When I 'accept' their request, the appointment pops into our calendars & reminders are automated.",
"How will Indian GDP be affected from banning 500 and 1000 rupees notes?",
"Why does understanding death philosophical?",
"Why are dogs considered omnivores?",
"What it is like to be cheated upon in a relationship?",
"How do I know if someone blocked my texts?",
"What are the most interesting foods you have eaten in any country?",
"What is it like to be a private banker?",
"What is journalism for you?",
"How can one increase concentration?",
"What are the pros and cons of the German Shepherd dog?",
"What is the difference between deism and agnosticism?",
"Why do male porn stars masturbate to ejaculate?",
"How much CGPA I require to get an admission for MTech CSE at IIT Madras?",
"Is there a biological reason that people cry when they are emotional?",
"What are 5 facts about the earth's crust?",
"Why does ISRO not use friction stir welding technology?",
"I wish to simulate a fake location for an app running on my iOS device. How do you fake a GPS location for iOS without jailbreaking as a non-coder?",
"What would be the best way to quit smoking?",
"Which is the best programing language for tcs?",
"Earthquake resistant homes?",
"Is Kristen Stewart a bad actress?  Why or why not?",
"Why do some Japanese guys try to look feminine? Don't the girls find it gross?",
"What are the five most popular sugar daddy websites?",
"What is the VTU 1st sem exam time table of 2016 (Dec)?",
"What is the best phone to buy below 15k?",
"How do we start a business?",
"What's the best near-death experience you've ever had?",
"Why do I keep getting fleas from my dogs?",
"What year did the letter J come?",
"Harvard College Courses: What is general shopping advice for Turkish classes?",
"How do I send message from one Android phone to another Android phone through bluetooth?",
"What are the most important books ever written?",
"What universities does Sigma Designs recruit new grads from? What majors are they looking for?",
"Can we do an M.Phil in India after doing Masters in UK (MA in Psychology)?",
"What universities does Powell Industries recruit new grads from? What majors are they looking for?",
"What are some of the best movie posters you have come across?",
"What are some examples of deuteromycota and how are they formed?",
"How racist is too racist?",
"Are there any differences between however and nevertheless?",
"Are Canada Geese really Canadian?",
"How do I find the zeros of the polynomial function [math]f(x)=\dfrac{1}{2}x^{3}-3x[/math]?",
"How do I edit my devices on my Google play account?",
"How can I become a good speaker?",
"How can I write a letter to Mr. Narendra Modi?",
"Who is more electable in a general Presidential election: Donald Trump or Ted Cruz?",
"Why do they name bastards Snow?",
"What do you think about the Bermuda Triangle?",
"Do Mexican girls like black guys?",
"Have you lived in a tiny house?",
"What is a boy/girl called when he/she is 1-6 years old, 6-11years old, 11-14 years old, and 14-18 years old?",
"Can you debeak cockerels at 8 months old?",
"What should someone do to overcome anxiety?",
"How do we avoid whey in Yogurt?",
"Im in love with my bisexual best friend who is also a guy and has a girlfriend, and I want to tell him. How do I move on?",
"What is the best university in Germany for an MS?",
"How do I maintain my peace of mind?",
"Which car has good build quality in india?",
"Why does massaging one's temples soothe a migraine or headache?",
"Which one is better among KMC Manipal and KMC Mangalore?",
"Why are my bestfriend still ignoring me?",
"What are the sensors available in Acer Liquid Z630S Android Smart phone by using CPU-Z App?",
"How do I keep motivation to learn a language?",
"What are the top assessment companies in India?",
"What does @ mean as an emoticon?",
"Is a pinkish discharge normal in early pregnancy? What causes it?",
"What are the best ways to properly finger yourself?",
"How do scientists work?",
"How many sponsored candidates are shortlisted for CMC vellore?",
"What is the different between Chinese wedding ceremony and western wedding ceremony?",
"What is the condition of tourism in Pakistan?",
"What is the different between offshore and onshore funds?",
"Why should one hate Shahrukh Khan?",
"What are the best self-help books you've ever read?",
"Is Evernote useful?",
"A title for my continuation to The Gift of the Magi?",
"What is a good song to lyric prank your best friend?",
"I argued with my gf that she made friends with the person that hit on her. She said I'm a control freak and she wants her freedom. What should I do?",
"How do I pass a drug test for methamphetamine?",
"How could start with open source development?",
"Why do dreams look so real?",
"Do cricket players really drink tea on a tea break?",
"How can I get entry in MIT?",
"Does a fetus breathe when it's inside a womb?",
"What are movies with incest scenes?",
"What are the signs that a guy has feelings for you or has a crush on you, but doesn't want to show it, so he hides it?",
"According to the International Federation of Robotics, how many robots existed in 2012?",
"Do you regret your divorce?",
"How much does your DNA change over time? If I were to clone myself 70 years from now, will the clone have the same hair color?",
"Is it right to tell a girl the you have feelings for her?",
"Is Donald Trump taking cocaine, as Howard Dean suggests?",
"Is it true that in order to be part of an elite or just rich and successful, you have to join a secret organisation otherwise no chance at all?",
"Which is more financially beneficial: being in a firm or teaching in an architecture college?",
"How can I see the Comedy Nights with Kapil live show?",
"Why is sandeep maheshwari not on Quora?",
"What is the biggest monster in Monster Hunter?",
"How can I convince people to stop blaspheming against the Holy Spirit?",
"Why can't I stop watching porn?",
"How can I start trusting any one?",
"What's your bucket list?",
"How did you first come across porn?",
"Which car services are available in Normal, IL? How good are they compared to taxis and relative to each other?",
"Why can’t charged molecules pass through the lipid cell membrane?",
"How does it feel to be a spouse of a renowned porn star?",
"What is the best hostel booking affiliate program?",
"How can the drive from Brooklyn to Staten Island be described, and how do these cities' tourist attractions compare to those in Queens?",
"What can I eat every day to be more healthy?",
"How do I make free calls to family members on Airtel Andhra Pradesh?",
"What would Hillary Clinton do now that the election is over?",
"Should I use Vicks Vapor Rub for a stuffy nose?",
"How I start prepare for UGC net English literature latest syllabus?",
"How did early Europeans get protein before the Columbian Exchange?",
"What is the best forum for graphic designers?",
"Is Alex Jones a satirical show?",
"Should I learn AngularJS 1.5 instead of AngularJS 2 if I don't know TypeScript?",
"Why can't we fall asleep on some days?",
"Which Marvel movies have not included Stan Lee cameos?",
"What are your views on Modi governments decision to demonetize 500 and 1000 rupee notes? How will this affect economy?",
"What does the 10/6 label on the Mad Hatter's hat mean?",
"Who wrote the Kars for Kids jingle?",
"Why is Saltwater Taffy candy imported in Greece?",
"What are the minimum requirements to enter MIT?",
"How do you answer a question on Quora?",
"Israel vs Iran: who would win?",
"When is it too late to learn the piano?",
"What are natural numbers?",
"Is One Plus 3T 4G VoLTE enabled phone?",
"How do I enter a new email ID which I can access to recover my Facebook ID?",
"How we can travel faster than light?",
"What is it like being a firefighter?",
"What are the factors that causes data inconsistency in distributed platform/application?",
"What are the differences between POCSO and sexual offenses in the IPC?",
"What is considered an illegal screen in the NBA?",
"Nothing excites me anymore. How do I regain that excitement?",
"What are the life lessons that Batman teaches us?",
"How do you stop a criminal's attempt to kidnap you so you escape unharmed?",
"How do I sell on Amazon?",
"Daniel Ek: When an we expect Spotify in India?",
"What are the top 10 books one should read in his or her early 20s?",
"Which book should I start with for the GATE preparation?",
"What is similar to 4Shared?",
"Can you get high if someone touches weed and then you shake their hand and then you eat something with that same hand?",
"Considering the current trend of information technology what is the future of print media?",
"What is the best recipe for chicken pizza?",
"What are some good places to learn mountaineering in India?",
"Do new table tennis balls damage rubbers?",
"My new Xbox one S can't connect to internet during setup. Any solutions?",
"Is it wrong for me to be content with my life?",
"Is gravity only a theory?",
"How could I become a fighter pilot when I have less than the required eyesight?",
"Operation executive salary in Infosys?",
"Have cavemen been scientifically tested?",
"Can climate change be reversed?",
"How should ask my crush for her number?",
"Why do I believe that gravitation force exist?",
"Did Mahabharata really happen?",
"Can Congress stop Presidents from starting a major war?",
"Is it safe to lose 25 pounds in 1 month?",
"What are some cute shounen ai series?",
"Why are police lights red and blue?",
"How do I post a question that was marked as needing improvement?",
"Who owns nature?",
"How can I install OBB/data file on an Android?",
"What is garbage value? And Why do we get garbage value in c?",
"How do I prepare for software interviews?",
"Does Rahul Gandhi have any chance to become next PM of India after Modi?",
"Is noon 12 am or 12 pm?",
"What is the difference between a comet and an asteroid?",
"Is chocolate milk good for you?",
"How should I study",
"Which country is best for higher education and work?",
"What is the painting on this image?",
"Which are the major highways in California and how are they compared to the major highways in Tennessee?",
"What's beyond our Universe?",
"Is growing of hair a physical or a chemical change?",
"What is the difference between culture and history?",
"What does it mean when a guy says I like you?",
"What will most likely cause World War III?",
"Is civil war likely after the US presidential election?",
"Which European country is the best for asylum seekers?",
"Where and how do the crop circles get generated?",
"Will baking soda help pass a urine test?",
"What is Zika virus and how is it transmitted?",
"What is the best way to learn algebra by yourself?",
"How does it feel to retake a class in college?",
"Does Google Display Network require any site to have it SEO (on-page and off-page optimized) first before they can proceed with GDN? Is this possible?",
"What is an actinomorphic flower?",
"What is the best place for sex?",
"Do people with anemia die younger?",
"How do you feel about the new MacBook Pro, late 2016?",
"Does covering your head while sleeping cause brain damage?",
"What are the major differences between Chinese culture and western cultures?",
"What are scraping techniques?",
"I am 29Y old. I have diabetic Type 2. Recently my sugar level was increased to 150 (fasting). I do exercise and eat whole grains. why this happening?",
"Is it healthy to eat egg whites every day?",
"What words rank the highest on Dictionary.com's difficulty index?",
"Why can't I feel remorse or empathy at all?",
"How many minutes of cardio a day should I do?",
"Why is my dog biting me?",
"How can I treat a severe foot sprain?",
"How can a severe crick in the neck be treated?",
"What are the best places to recommend foreigners to visit in Nepal?",
"Who do I activate the dlc of skyrim in a laptop? Ive got it working on my computer after doing the command lines, but did the same on laptop, to no use..",
"How should I prepare for HSBC GLT placement tests?",
"Did any Indian writers/authors ever use a pen name?",
"How do I register institute providing training in various programming languages for vocational courses as it will exempt it from the service tax?",
"How imminent is world war III?",
"How do you write a song?",
"What could be Narendra Modi's next move after demonetization?",
"If you have me, you want to share me. If you share me, you haven't got me. What am I?",
"What is an interesting fact that you know and I don't, but shouldn't?",
"What is the problem with controlled fusion?",
"Where do I find 3ds emulator for android?",
"I want to start my clothes boutique in India, from where can I buy cheap wholesale clothes?",
"How can I become a true computer science engineer?",
"Is it necessary to unlock bootloader before rooting Android phones?",
"What is bss engineer?",
"Why do I get punished by Quora moderators when I put Israel and Judaism in a negative light?",
"What can you do in lucid dreams?",
"What does it feel like to be beautiful?",
"Is it possible to do CA after 12th Science?",
"How can I hack someones whatsapp account?",
"What is it like to study math at UCLA?",
"What is the best lesson in life?",
"What are some Interesting mobile apps?",
"How will Trump's presidency affect Indian students who are planning to do a PhD in the US?",
"What are the various Batman movies in the series? (In order)",
"What are the best daily life hacks one can use to make his life easy?",
"How much weight will I lose by not eating for a week?",
"What is your favourite anime character and why?",
"How do ATM machines work internally?",
"How many Mechanical Engineers graduate from India per year?",
"How do I start a successful private equity firm?",
"What are most underrated date activities?",
"What are some common facts every mechanical engineer should know?",
"What can be the medium budget to visit best places in Kerala for three members (2-3 days)?",
"Why is Quora Digest filled with questions about Google, IQ, and China?",
"How would you destroy the world?",
"How can I earn money from YouTube?",
"What are the differences between particles and molecules?",
"On Facebook, how can I add mutual friends?",
"What is Russian president Vladmir Putin like as a person, to his closest friends and family?",
"How do I start writing again?",
"If time started because of the big bang happening then how could the big bang start because there was no time for the big bang to start?",
"How does it feel to be in a relationship than being single and how does our life changes when we are in a relationship?",
"How can I start civil service exam preparation from scratch?",
"What are the non-invasive blood glucose monitoring systems abroad?",
"What is the difference in pleasure between masturbation and sex?",
"How do I start a solar energy business in egypt?",
"Can my PC with specs 2 GB DDR2@ RAM, Intel Core Duo 3.5 GHz, NVidia GeForce GT 610 3gb DDR3 run Assassin's Creed Syndicate and GTA V?",
"Do you have any psychic abilities?",
"How do I manage time for studies?",
"What is the academic calendar at XLRI?",
"What is your take on Urjit Patel as the new RBI governor?",
"Why do you want to be to president?",
"Why India does not have friendly relations with it's neighbouring countries?",
"Do Trump voters care that he has reneged all his campaign promises?",
"Can I learn while sleeping? If so, how?",
"Can you play Asian Playstation 4 games on a European Playstation?",
"How do I stop being addicted to porn?",
"Why did British engineering and manufacturing skills decline so dramatically in the 60s, 70s and 80s, especially when compared with Germany's?",
"How do I work with machine learning researchers after graduation?",
"What is the future for iOS Developers?",
"What is the meaning of life? Whats our purpose on Earth?",
"How do I be a boyfriend?",
"How is time travel possible?",
"How can one get a fuller face?",
"Is it too late for me at the age of 25 thinking to start a career in photography?",
"What’s the best time to have sex?",
"Can we weld steel and aluminum together?",
"Which YouTube video has the highest like/dislike ratio?",
"What is solution to Kashmir issue?",
"If you dug a hole through the earth, and came out the other side what would happen?",
"Can we create free energy?",
"What should I do for Web design?",
"What's the funniest highbrow joke you've ever heard?",
"How do I find the phenotypic ratio?",
"Why does Saturn benefit a house it sits in slowly?",
"Who is the most academically qualified Bollywood celebrity?",
"Is there a difference in quality between wired and wireless headphones? If so, why?",
"What are some movies that everyone needs to watch at least once in life?",
"Can World War 3 ever take place?",
"How can eating prunes help during a constipation?",
"You have given all statement as correct in UNCCD question in CSE prelim 2016. While many coachings have taken 2nd statement as wrong.?",
"What would be today’s technology had we never realized the value of binary numbers and harnessed it to produce digital technology?",
"What is the best way to invest in oil and natural gas?",
"Is Arnab Goswami pro-BJP?",
"What are some good sources for learning NuGet?",
"How would do you describe a person with lots of interests?",
"Is it possible to turn off indicator light on a dahua camera?",
"Why is Barack Obama so important for the world?",
"What is the reason Pakistan supports terrorism?",
"How do I can stop hairfall?",
"In your opinion, what is the best classical song of all time?",
"What are some unusual aspects about politics and government in Hungary?",
"What is the aim?",
"How should I respond to my boss who fired me via email?",
"What are cheap and budget stay options in North Goa?",
"Is there any other website similar to Quora?",
"What are the conditions in European refugee camps?",
"How do you know that your fiance loves you?",
"Can somebody explain to me how to do this problem with steps?",
"How do I develop my presence of mind?",
"Mathematical Fallacies: What is wrong in this proof that 2+2 = 5?",
"Will it help CIBIL score if I pay off my written-off amount?",
"Should the Hobbit be considered a canonical Tolkien work?",
"What do Japanese think about Malaysian?",
"Is the Har Ki Dun trek easy?",
"What are the good websites to learn C programming for begineer?",
"Will the Supreme Court's decision of playing the National Anthem before movie screenings affect your patriotism?",
"If the United States has a female president, will her husband be called the first gentleman? What will Bill Clinton be called if Hillary is elected?",
"How can I get MOOC/E-learning through online web and video courses related to filmmaking & production developed by Indian professors?",
"Mobile Number Portability finally will start on May 3. Do network providers really agree to this?",
"Why do people hate twilight saga?",
"Do you believe imperialism left a positive or negative legacy in the Indian subcontinent and in Africa?",
"Why is C the best programming language?",
"How can I improve my spoken English ability?",
"How can I have gay sex?",
"I'm transferring to a school with a US curriculum (taking the IBDP) from a Philippine school w/ a percent average grading system. How do I get my GPA?",
"How do I make money with YouTube?",
"How do I find love in life?",
"Which option is better to reduce weight, swimming or gym?",
"Is there any way to get rid of gynecomastia?",
"Which payment gateway in Saudi that using to collect and pay money from/to multiple ?",
"Are there any scientific reasons behind Hindu temples?",
"Is (male) circumcision required in Islam?",
"Where can I get super high quality photos for any photo booth services in Sydney?",
"How can I find out whom I sent a friend request to on Instagram?",
"How can I control on my anger?",
"What are genders?",
"How do I get off Quora?",
"How long can raw and cooked sausage last refrigerated?",
"What are the best available smartphones gadgets?",
"How does it feel to be a closeted gay in India?",
"Can we switch roles at Amazon?",
"What happens if dictatorship is continuing in the present days?",
"What makes a great cup of coffee great?",
"Is the US election rigged?",
"Why hasn't Gayle Laakmann McDowell/careercup created a MOOC or a coding bootcamp?",
"What is fermentation? What are some products of fermentation?",
"Should there be a war between India and Pakistan for Kashmir?",
"What is the best way to get you food stamp card?",
"What are some real world example of encapsulation and abstraction and how are they different, yet related?",
"What are ways to deal with fabricate security and insurance of android application?",
"What is the best accordion for beginners to learn on?",
"Role of junior leaders in Indian army?",
"What's your opinion about the decision on removal of 500 and 1000 rupees currency notes?",
"What are some of the most mind-blowing facts about Bengaluru?",
"If both the parents have blood group B+, can the child have A+?",
"Which book is best for Neet chemistry?",
"What is the essence of enlightenment?",
"Why are so many questions posted to Quora that are so easily answered by using Google?",
"How should I answer if an interviewer asks me to sell a pen or any other product as I am pursuing a MBA?",
"What are some great side dishes for a minestrone soup?",
"How much is the maximum gold you can take when flying from India to USA?",
"If my reservation status is RAC, does it mean the seat has been confirmed?",
"How does a new website protect its design and user interface from copycats?",
"How can I improve my skills?",
"Is it possible to use SPI between AVR and Raspberry pi?",
"Which are the best movies of 2016?",
"What would be effect of 500 and 1000 Rs notes ban?",
"What are some of the best photos?",
"Why students run away from home?",
"In C++, what are access modifiers?",
"Can you analyze history, or is it unscientific?",
"What are some interesting theories about life after death?",
"Do I need to get a tetanus shot again?",
"How light bend with gravity?",
"What does it mean to hike up your skirt?",
"How many new cars are sold by Maserati in the US each year?",
"How do you send a private message to someone you're following on Quora?",
"How do you train a white Pitbull with brown spots?",
"What is the difference between a turkey and a chicken?",
"What are some of the most surreal questions asked on Quora?",
"What is the difference between IT and computer science engineering?",
"When will the best time for having sex?",
"How can I consult a good free online astrologer?",
"Why we don't feel sympathy towards everyone?",
"Why do brothers hate sisters?",
"What is the best site for downloading Kannada films in torrent form?",
"What are some of the most gruesome causes of death?",
"What is latency in telecom?",
"Is senior residency at Hindu Rao Hospital teaching experience?",
"What behavioral adaptations do pandas have?",
"Is Textile Engineering Good?",
"What is the fastest production car?",
"How magnets are made?",
"What's the street value of A332?",
"What are the qualifications for being an FBI or CIA agent?",
"What is the best operating system for the PC in 2014?",
"Why are major Indian TV channels absent in northeast?",
"Hypothetical scenario: Our actual credit card system & banking never existed before. How would you implement a digital currency on the Internet today?",
"How does Quora quickly mark questions as needing improvement?",
"How will I contact a good hacker?",
"What are the best horror novel in 2016?",
"What is the most beautiful thing that you have ever seen?",
"What are the most important things for living a good life?",
"What is the meaning and purpose to life?",
"What should I do when my friends betray me?",
"I'm 15 year old my height is 5 feet 7 inches and my weight is 50 kg what should I do to gain weight?",
"Why is Saltwater taffy candy imported in China?",
"Is there a different price over the Internet than in person when trying to book a room in Mexico City from the US?",
"Why did Venuetastic fail?",
"Which were some of the most amazing responses you have got with Cortana, Siri or Amazon Echo?",
"What is most important in life - money or values?",
"Who are the best hackers in India?",
"Should the Indian education system be changed?",
"What are the multiple uses of hollow columns?",
"Which are some commonly mispronounced words?",
"Why is it that every teen girl has a crush on her mathematics teacher? Is it the intelligence or their behavior?",
"Is it too late to go to medical school and become a doctor?",
"Where can I buy best quality commercial innerspring sofa bed in Chatswood West?",
"If you screenshot someone's Instagram video, will they get notified that you screenshotted it?",
"What government exams, other than the GATE, can final year computer science students give?",
"What sentences use all 26 letters without any repeats?",
"What is the effect of hypodensity of white matter in parietal lobe of brain?",
"What is your job and your salary? Are you satisfied with your current job?",
"Psychopaths: Do you find babies cute?",
"What is the opera song with a choir used for horror movies?",
"Would a woman in the Catholic Church be shunned or ostracized for having a sexual relationship with a priest?",
"If a Canadian gets a tattoo in America, do they have to declare the cost when returning to Canada?",
"How can I see who blocked me at Facebook?",
"Why has there been a scarcity of high quality fantasy films?",
"Who are some of great coders from Tamil Nadu?",
"What do think of when you hear the word elect?",
"Which is the best programming language to learn in 2017?",
"What is the ultimate way to serve humanity?",
"How can I calculate 72 hours from now?",
"How hard was it for Jimmy Wales to immigrate to the UK?",
"Cochin to London etihad is the change over time of 1hr sufficient in Dubai?",
"What is Quora's algorithm for sorting answers to a single question?",
"What will be the resolution one should have for the year 2016?",
"What are Balaji Viswanathan's views on caste based reservations in India?",
"Jawed habib haircut prices?",
"Does any one have ebook of answers of wren and Martin grammer and composition?",
"What is [math]x[/math] if [math]x+\left(\dfrac{1}{x}\right) =0[/math]?",
"Whenever its about “her” its a very special feeling. Tried hard to forget her but she's alwys spcl. Should I stop talking to her even as a friend ?",
"What are Mutual funds? How do they work?",
"How has the vertebral column anatomy changed through time?",
"Which acoustic bass guitar is the best?",
"Which universities in the US offer more management content in the management information systems curriculum?",
"My maths have become extremely weak and I am in class 12th. How can I improve my maths so that I can clear my JEE exams next year?",
"What is the main difference between socialism and communism.?",
"How do I change my Facebook password?",
"How is the word 'valiant' used in a sentence?",
"Why I feel dizzy when I am playing some 3D games but others do not make me feel like this? Are there any tricks in developing 3D games to avoid this?",
"How do payroll companies make money?",
"What are the most underrated and overrated movies you've seen?",
"For what use cases do you think deep learning and neural networks overkill and simpler models work better in practice?",
"Which one to learn, C++ or C#?",
"Will a Fitbit accurately track my activity if I am riding a bike?",
"What is the best evidence for a historical Jesus?",
"Which free online language classes would allow me to go from 0 to fluent in Portuguese given their provided courses of study?",
"How do the PM and Prez get women?",
"What are some of the best part-time jobs where you can work from home and make some good cash?",
"Does Trump have a chance at winning presidency?",
"What if I shift my job from e-commerce to cloud computing?",
"How can I meet Suresh Raina?",
"What is the name of the song in which picturized on Madhuri Dixit and Ranbir Kapoor and is from which movie?",
"What is the function of nucleoplasm in a plant cell?",
"Can fossil records be used as evidence for evolution? If so, how?",
"What is the Hizmet movement?",
"Could CAT exam and MAT exam take place on same day (4th December 2016)?",
"What mythical creatures are in the Bible?",
"Which one is good: oral, anal, or vaginal sex?",
"What are the winter weather conditions like in Cincinnati, OH?",
"What stocks are the best to invest in right now?",
"How do we improve reading skills of children?",
"What should I do if someone has posted a porn video under my name?",
"Do you lose nutrients & calories when you have diarrhea?",
"What are the safety precautions on handling shotguns proposed by the NRA in Alaska?",
"What is the benefit of going Walking every morning?",
"Are there any martial artists who started later in life and went on to become champions?",
"How do I get my ex back?",
"Which framework should i choose for cross-platform mobile development?",
"What is the best way to prepare to IELTS?",
"How do I know if the girl am dating online truly live me for real?",
"What area of games programming is most mathematically involved and suited to a math major?",
"What are the differences between larceny and robbery?",
"Is graph theory counted as a prerequisite for machine learning?",
"What are the best schools to study Natural language Processing in India?",
"Will Ted Cruz supporters vote for Donald Trump?",
"What is a GDP?",
"How do I make a girl who is a newly joined junior in my college to fall in love with me?",
"What are the home remedies for piles or anal fissure?",
"How many words are actually needed to learn for the GRE and what is the correct method to prepare for the GRE verbal? ?",
"Is the soul immortal?",
"What are some of your own personal Moon in the 3rd House stories and experiences?",
"What can be done to reduce the pollution of India?",
"Is government liasioning legal in India?",
"What is the best place to celebrate New Year 2017 in Hyderabad?",
"What is working hard (not in terms of studying)?",
"Can I upgrade Windows 32 bit to 64 bit Windows 8.1?",
"Which were some of the bad experiences you had in life?",
"Why is Timbaland famous?",
"Can you get a list of individual telephone numbers?",
"Do you have to wake up during REM sleep to remember your dreams?",
"What are common required and elective courses in agriculture?",
"How do I learn how to sing?",
"Who is capable of ending Google's monopoly in search?",
"Can an auto immune disease cause insomnia?",
"Does GTA IV work in Windows 7?",
"Which is the best SSC and banking training insititute in Chandigarh?",
"Which is the best PMP Certification course provider in Bangalore?",
"What is difference between net and gross income?",
"How can I wake up early in the morning?",
"Why do you love her?",
"I missed the IIT. What should I do?",
"What is the difference between the iPhone 6s and iPhone 6s Plus?",
"How can one improve a credit score by 100 points?",
"My crush likes me back; what do we do now?",
"Who is the most powerful character in Skyrim apart from Alduin?",
"Can a Muslim guy date a non Muslim girl? Is it based on how religious the individual is or are there other factors to it?",
"What are your comments on this picture?",
"When are the roads most slippery during rain?",
"How do you prove the Heisenberg uncertainty principle experimentally?",
"What is the IELTS all about?",
"How do I lose weight without doing any sport?",
"Why do digital cameras have shutter sound?",
"What's it like dating a gangster?",
"What were the main and most important political causes of World War 1?",
"How do I get over the fear of everything?",
"Which city in India has the best weather?",
"What is the difference between HDD and SSD in layman's terms?",
"What does it mean if a dog vomits white foam?",
"Does my life hold any significance to the world/universe?",
"How is the job situation in New Zealand for computer science graduates?",
"How would I develop an e-commerce website?",
"How do you get a micro SIM card out of an iPhone 4?",
"What can I do to improve my question on Quora?",
"If one of the people catches feelings, in an established friends with benefits arrangement, how can we drop the feelings going forward?",
"What are some tips for someone trying to teach themselves to sing?",
"If climate change scientists are right, why do they worry so much about public relations and packaging?",
"What is the main reason for all the problems in India?",
"What is a good substitute for milk in macaroni and cheese?",
"How can constipation cause dizziness?",
"Is it possible to make doctor's review app using which patients can share anonymously all treatment given by that doctor, suggested medicines,?",
"What are some of the pros and cons of a Hillary Clinton presidency?",
"What are the best films that take place in one room?",
"Is it normal if your sperm doesn't shoot out during ejaculation?",
"Which is the best coaching center for SSC and Banking in Chandigarh?",
"What's the next number in the series 1,1,1,2,2,2,6,6,6?",
"What are the best things to do on Halloween?",
"I wish to start investing in Equity and Mutual Funds. Where should I open Demat account for best rates, transaction charges and so on? I am NRI.",
"Why do companies issue bonus shares?",
"How can changing 500 and 1000 rupee notes end the black money in India?",
"What should I major in (College) that won't leave me unemployed (other than Engineering, Law, Medicine)?",
"Who are the best custom kiosk manufacturers in India?",
"Are there any telescopes powerful enough to view evidence left behind from NASA's moon landings?",
"Is there any architectural complex/center/forum/hub anywhere in the world? As a third space.",
"How many keywords are there in AutoHotkey Scripting Programming Language in the latest version?",
"What is the hardest thing(s) about raising children in Ukraine?",
"What is the best source to learn stock market online?",
"Why does India sabotage and badmouth all economic projects which its neighbouring counries have in the world?",
"What does a wet vagina feel like for a man?",
"Will Thursday Night Football increase ratings for CBS on Thursday nights rather than the Big Bang Theory?",
"How can I grow taller at 17?",
"Have you ever been fired?",
"How on earth would I dress like a workout guy from the year 1990 in the summer?",
"My girlfriend has stopped talking to me. What should I do?",
"What will the real estate look like now after the 500 and 1000 scraping?",
"What are the best interview questions ever asked?",
"I trust people very quickly and as a result always have been betrayed? What do I do not to trust people and still hold the relation simple?",
"Who are the best headhunters in Mumbai?",
"What is the DHP vaccine for dogs for? Is it necessary?",
"What are the differences between Asia and Africa? What are the similarities?",
"Has wizard magic been scientifically tested?",
"Why is contract law important?",
"When will moto G3 (Moto G 3rd gen 2015) get Android 7.0 (Nougat) update?",
"Prove that SNR of power = (SNR of voltage) sequare?",
"What are the best riddles by the Riddler (Batman)?",
"Why there is so much nudity content in Game of Thrones?",
"How can I get followers and comments on my blog?",
"I have only 2 months for my CA CPT exams how do I prepare?",
"What programming language should I learn if I want to do a 2D MMORPG game?",
"What is your view on the recent demonetization in India?",
"Why was cyrus mistry removed?",
"How do you cancel USAA auto insurance?",
"Why have I been so angry lately?",
"How do you form a hypothesis, since you haven't done any testing and don't have any test results yet?",
"What are the consequences of trolling?",
"I am frightened of Arvind kejriwal, he may kill me, What shall I do?",
"What disadvantages do Apple computers/laptops have over other brands?",
"What is the first moment you remember in your Life?",
"What can I do after completing BDS?",
"Does all Muslims hate Narendra Modi?",
"I'm 18. What should I do?",
"What are some really good and famous romantic comedy movies?",
"How realistic is it to get a second bachelors degree in Math as an international student holding a first bachelors degree in Accounnting?",
"How is it possible to believe in the Old Testament in which there is just one God and at the same time believe in Trinity?",
"How should I start meditating?",
"Can an infinite amount of dark or vacuum or gravitational energy be created with expansion?",
"Is Bihar really developing under mahagathbandhan sarkar?",
"How can homeopathic medicine not have side-effects?",
"How do you determine what's a good investment brokerage and what's not?",
"What is the scope of supply chain management in India?",
"Are the number of pistons equal to number of number of cylinders?",
"Should you post picture on social media?",
"Can we control our actions in a dream?",
"How did you managed long distance relationship?",
"What are the chances that I could just ask a rich person for a million dollars and actually have them give it to me?",
"What happened to Hong Kong movies and TV drama? Why did they decline so much?",
"Did Trump win the election?",
"What are the best wallpaper apps for iPhones?",
"In what format should I send book for printing?",
"Why does the caste system still exist in India?",
"How do I get a boyfriend for age 13?",
"What is rank at 550 marks in NEET 2016?",
"Is the dynamic/flexi-pricing harsh on middle class people?",
"Can I overdraft my Wells Fargo account?",
"What are some new marketing techniques for language schools?",
"How much do olympic gold medalists earn?",
"What are the easy ways to earn money online?",
"What is reactance in a capacitor?",
"Is it true that the cost of living in SV and the Bay Area is so high that new grads making 150k+ have a hard time finding affordable housing?",
"What's the best school in the world?",
"Why is Saltwater taffy candy imported in Australia?",
"What is value of 0?",
"Which are the best part-time jobs to do in Bangalore?",
"How do I become an attractive girl?",
"What are some of the best music albums ever?",
"Realistically speaking, what would happen to the USA if Donald Trump wins Presidency in the 2016 elections?",
"What are symptoms of autism in kids?",
"What's it like to be a non-smoking mother of smoking children?",
"What is life without dreams?",
"How comfortably can I live in Washington DC on a $80,000 salary?",
"How do you find out if a girl has a boyfriend?",
"What are health benefits of red lentils?",
"What are some math related working models for class 10th?",
"How could I gain weight in a healthy way?",
"What kind of animal did this?",
"How does Anil Ambani benefit from Rafel fighter jet deal?",
"Is YouTube Red's offline feature as good as downloading the video itself?",
"How do I know if my spouse is my soulmate?",
"How do I get to be a people person?",
"How does a long distance relationship work?",
"HOw do I speak Fluent English?",
"Considering your position as Secretary of State gave you insight into the US's drone program, what will you do to reform the targeting process?",
"What exactly is MIKE2.0 (in layman's terms)?",
"Why don't buffalo and the like evolve to band together against lions and cheetahs instead of run away?",
"Where can I find a hacker for good cause?",
"How can I change my snapdeal account's mobile number?",
"What are some tips on making it through the job interview process at S & T Bank?",
"What are the main imports and exports of Venezuela, and how does Venezuela's industry compare to Cuba's?",
"How did Lucifer and Gabrielle relate to each other?",
"What are some good movies to watch?",
"How do I install Cydia without jailbreak on iOS 9.3.5.?",
"What can I do to get a job at Microsoft?",
"Why is 'fahrenheit 451'  perceived as dystopia?",
"What is your review of Love in Thoughts (2004 movie)?",
"Is it physically possible to travel back in time?",
"Why am I only awkward with some people but not others?",
"How do I recover deleted messages in Facebook?",
"How is the compensation system in Uber?",
"Is it feasible for Flipkart to offer an EMI on debit cards? What are the different factors involved?",
"How do I define tasks vs milestones vs deliverables in an agile scrum methodology?",
"Life can be boring. What to do?",
"Where can I buy meldonium in Canada?",
"What would be a cool way to commit suicide?",
"I accidentally took my blood pressure medicine twice, will I be ok?",
"Do you have any paranormal experience?",
"Which 2G Band (900/1800Mhz) was sold during 2G spectrum scam?",
"I am a straight A student but have no motivation or will whatsoever to go to school. Can someone help me fight this?",
"Which is the best shares to purchase and sale daily trading?",
"I and my girlfriends private partstouched each other.can she become pregenant?",
"Could we use cherenkov atmosphere radiation (with gamma rays or similar) to image the surface of a planet from here with ground based telescopes?",
"What is a good song for lyric prank?",
"How can I convert raw files to JPEG in photos in a MacBook?",
"What is the best age to teach a child how to swim?",
"Which is less healthy for your body, beer or Pepsi?",
"Where can I find my mentor?",
"What would cause an AMP to cut out?",
"How do I score good marks in mathematics?",
"Why does Facebook Messenger use long polling over WebSockets?",
"What are the chances of ww3?",
"Is there some way to identify genuine JBL speakers, as fake JBL speakers are also sold in market?",
"I took some moocs before college and now I feel like college is horrid, what do I do?",
"What are the application of binary search trees?",
"What are the differences between Hindustani classical music and Carnatic music?",
"How can we solve the issue of kashmir?",
"Do you think of mathematics as art or science?",
"Is scientology a fraud?",
"Who will win the 2016 presidential election?",
"Why did Polyvore remove Pasha Sadri as CEO and replace him with head of product, Jess Lee?",
"Which is the best book to understand special relativity?"]
